name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/Miping/backend

            echo "Pull latest code"
            git fetch origin
            git reset --hard origin/main

            echo "Create backend env"
            printf "%s\n" "${{ secrets.BACKEND_ENV }}" > .env

            echo "Create cert folder"
            mkdir -p certs

            echo "Create Kafka certificates"
            echo "${{ secrets.KAFKA_CA_CERT }}" > certs/ca.pem
            echo "${{ secrets.KAFKA_SERVICE_KEY }}" > certs/service.key
            echo "${{ secrets.KAFKA_SERVICE_CERT }}" > certs/service.cert
            chmod 600 certs/*

            echo "Restart docker containers"
            docker compose down
            docker compose up -d --build

            echo "Waiting for PostgreSQL..."
            sleep 8

            echo "Run DB scripts"
            docker compose exec -T backend node src/db/init.js
            docker compose exec -T backend node src/db/migrate.js
            docker compose exec -T backend node src/db/seed_superadmin.js

            echo "Deployment finished"
